// 2026-10-01 11:53 CEST: Acht Werkstattaufträge, positionsgebundene demontierbare Prüfteile und 3D-Probefahrt mit Tacho ergänzt.
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
const $=id=>document.getElementById(id),view=$('view'),keys=new Set(),ray=new T.Raycaster(),pointer=new T.Vector2();
const missions=[
{part:'vr',name:'Bremsbelag vorne rechts',issue:'Bremsbelag verschlissen',reward:180},
{part:'hl',name:'Reifen hinten links',issue:'Reifenflanke beschädigt',reward:220},
{part:'vl',name:'Bremsbelag vorne links',issue:'Bremse schleift',reward:190},
{part:'hr',name:'Reifen hinten rechts',issue:'Reifen porös',reward:230},
{part:'lightL',name:'Scheinwerfer vorne links',issue:'Abblendlicht ausgefallen',reward:160},
{part:'lightR',name:'Scheinwerfer vorne rechts',issue:'Scheinwerfer beschädigt',reward:170},
{part:'battery',name:'Batterie im Motorraum',issue:'Startspannung zu niedrig',reward:240},
{part:'vr',name:'Reifen vorne rechts',issue:'Reifen hat einen Höhenschlag',reward:260}
];
let progress={completed:0,credits:0};try{const v=JSON.parse(localStorage.getItem('garage-drive-progress-v1')||'null');if(v&&Number.isSafeInteger(v.completed)&&v.completed>=0&&Number.isSafeInteger(v.credits)&&v.credits>=0)progress=v}catch{}
let phase='inspect',selected=null,speed=0,distance=0,steering=0,cameraMode=0,last=0,started=false,down=null;const parts=new Map(),pickables=[];
const scene=new T.Scene();scene.background=new T.Color('#192c40');scene.fog=new T.Fog('#192c40',30,110);const camera=new T.PerspectiveCamera(60,1,.1,180);camera.position.set(6,4.5,8);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;view.append(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;orbit.minDistance=3;orbit.maxDistance=16;orbit.maxPolarAngle=1.48;
const mat=(c,m=0,r=.5)=>new T.MeshStandardMaterial({color:c,metalness:m,roughness:r}),red=mat('#a92337',.55,.25),glass=mat('#31576a',.3,.2),black=mat('#141b22'),metal=mat('#aabdc8',.85,.25),tireMat=mat('#12171b',0,.9),road=mat('#394450'),accent=mat('#5ce6cc',.3,.3);
function add(parent,geo,m,x=0,y=0,z=0){const a=new T.Mesh(geo,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}function box(p,w,h,d,x,y,z,m){return add(p,new T.BoxGeometry(w,h,d),m,x,y,z)}function soft(p,w,h,d,x,y,z,m,r=.1){return add(p,new RoundedBoxGeometry(w,h,d,4,r),m,x,y,z)}
scene.add(new T.HemisphereLight('#d4edff','#283744',2));const sun=new T.DirectionalLight('#fff0d9',3);sun.position.set(-5,10,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-20;sun.shadow.camera.right=20;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;scene.add(sun);
const ground=box(scene,120,.16,120,0,-.14,0,mat('#345249'));ground.castShadow=false;const workshop=new T.Group();scene.add(workshop);box(workshop,17,.12,18,0,-.01,0,mat('#445363'));box(workshop,17,7,.25,0,3.4,-9,mat('#25394a'));for(const x of [-8.4,8.4])box(workshop,.25,7,18,x,3.4,0,mat('#25394a'));for(const x of [-5,5]){soft(workshop,3,.11,.55,x,6.6,-3,mat('#8fffea'),.05);const fill=new T.PointLight('#86fce2',22,9);fill.position.set(x,5,-3);workshop.add(fill)}
const track=new T.Group();track.visible=false;scene.add(track);box(track,18,.04,110,0,.02,-36,road);for(let z=-85;z<20;z+=8)box(track,.12,.05,3,0,.06,z,mat('#f8ebbf'));for(const x of [-8.7,8.7])box(track,.17,.05,110,x,.06,-36,mat('#f8ebbf'));
const car=new T.Group();scene.add(car);soft(car,2.12,.55,4.4,0,.88,0,red,.2);soft(car,2.05,.18,1.3,0,1.12,-1.55,red,.1);soft(car,2.05,.18,1.1,0,1.1,1.57,red,.1);soft(car,1.78,.64,2.1,0,1.4,-.2,red,.23);soft(car,1.6,.31,.9,0,1.58,-1,glass,.05);soft(car,1.6,.27,.66,0,1.56,.67,glass,.05);for(const x of [-.9,.9])soft(car,.06,.3,1.05,x,1.5,-.2,glass,.02);soft(car,1.1,.23,.07,0,.75,-2.25,black,.03);for(const x of [-.36,-.18,0,.18,.36])box(car,.035,.19,.03,x,.75,-2.29,metal);for(const x of [-.9,.9])soft(car,.19,.11,.29,x*1.1,1.37,-.87,red,.04);const antenna=add(car,new T.CylinderGeometry(.012,.02,.72,8),black,.65,2.04,.55);antenna.rotation.z=.16;
function part(id,x,y,z){const group=new T.Group();group.position.set(x,y,z);group.userData={id,home:new T.Vector3(x,y,z),target:new T.Vector3(x,y,z)};car.add(group);parts.set(id,group);return group}function selectable(group,mesh){mesh.userData.part=group;pickables.push(mesh);return mesh}
for(const [id,x,z] of [['vl',-1.17,-1.44],['vr',1.17,-1.44],['hl',-1.17,1.44],['hr',1.17,1.44]]){const g=part(id,x,.4,z);const tyre=add(g,new T.CylinderGeometry(.39,.39,.27,32),tireMat);tyre.rotation.z=Math.PI/2;selectable(g,tyre);const rim=add(g,new T.CylinderGeometry(.25,.25,.29,32),metal);rim.rotation.z=Math.PI/2;selectable(g,rim);const face=x>0?.16:-.16;const ring=add(g,new T.TorusGeometry(.22,.027,8,32),metal,face,0,0);ring.rotation.y=Math.PI/2;selectable(g,ring);for(let i=0;i<6;i++){const spoke=box(g,.03,.06,.4,face,0,0,metal);spoke.rotation.x=i*Math.PI/6;selectable(g,spoke)}}
const beams=[],stops=[];for(const [id,x] of [['lightL',-.79],['lightR',.79]]){const g=part(id,x,1.04,-2.22);const lightMat=new T.MeshStandardMaterial({color:'#f5fbff',emissive:'#bcefff',emissiveIntensity:3});selectable(g,soft(g,.42,.13,.08,0,0,0,lightMat,.03));const spot=new T.SpotLight('#bdefff',60,18,Math.PI/7,.5,2);spot.position.set(x,1.04,-2.3);spot.target.position.set(x,.2,-10);car.add(spot,spot.target);beams.push(spot);const tail=soft(car,.38,.15,.06,x,1.02,2.23,new T.MeshStandardMaterial({color:'#f23a42',emissive:'#ee2838',emissiveIntensity:2}),.025);const glow=new T.PointLight('#ff303a',0,5);glow.position.copy(tail.position);car.add(glow);stops.push(glow)}
const battery=part('battery',.44,1.30,-1.58);selectable(battery,soft(battery,.47,.28,.37,0,0,0,black,.04));for(const x of [-.12,.12])selectable(battery,add(battery,new T.CylinderGeometry(.045,.045,.05,10),metal,x,.16,0));
const css=document.createElement('style');css.textContent='header,.hud,.controls{background:linear-gradient(110deg,#15313e,#0b1728)!important;border-bottom:1px solid #75e7cb40}#view{position:relative}#dash{position:absolute;right:16px;bottom:16px;width:162px;height:162px;border:2px solid #7aedd8;border-radius:50%;display:none;place-items:center;background:radial-gradient(circle,#1b4250,#081522 72%);box-shadow:0 0 32px #5fe8d873,inset 0 0 18px #000b;color:white;pointer-events:none}#dash.on{display:grid}#dash strong{font-size:2.3rem;line-height:1}#dash small{color:#75e7d3;letter-spacing:.15em}#needle{position:absolute;left:50%;top:19%;height:57px;width:3px;transform-origin:50% 100%;background:#ff6d68;box-shadow:0 0 12px #ff6d68}.dashText{display:grid;text-align:center;margin-top:45px}.dashScale{position:absolute;top:20px;color:#9cc6c7;font-size:.7rem}#summary{position:fixed;inset:0;z-index:8;background:#050a16cf;display:none;place-items:center;padding:18px;backdrop-filter:blur(10px)}#summary.show{display:grid}.result{width:min(490px,92vw);padding:30px;border:1px solid #5ce6cb88;border-radius:24px;background:linear-gradient(145deg,#203c4c,#0b1526 75%);box-shadow:0 0 80px #50e9d22b;text-align:center}.result h2{font-size:clamp(1.8rem,6vw,3rem);margin:.2em 0}.result p{color:#bfd2db;line-height:1.6}.result button{background:#68e7ce;padding:15px 23px;border:0;border-radius:12px;font-weight:900;cursor:pointer}.tag{color:#6debd2;letter-spacing:.14em}.amount{font-size:2rem;color:#ffd484;font-weight:900}';document.head.append(css);
const dash=document.createElement('div');dash.id='dash';dash.innerHTML='<div class="dashScale">0 · 60 · 120</div><div id="needle"></div><div class="dashText"><strong id="kmh">0</strong><small>KM/H</small></div>';view.append(dash);
const summary=document.createElement('section');summary.id='summary';summary.innerHTML='<div class="result"><div class="tag" id="resultTag"></div><h2 id="resultTitle"></h2><p id="resultText"></p><div class="amount" id="resultAmount"></div><p id="resultStats"></p><button id="resultNext"></button></div>';document.body.append(summary);
const job=()=>missions[progress.completed%missions.length],message=s=>$('message').textContent=s;function hud(){document.querySelector('header span').textContent=`AUFTRAG ${String(progress.completed+1).padStart(3,'0')} · ${job().name.toUpperCase()}`;$('speed').textContent=`${progress.credits} CR · WERKSTATT`}
function result(tag,title,text,amount,button,callback){$('resultTag').textContent=tag;$('resultTitle').textContent=title;$('resultText').textContent=text;$('resultAmount').textContent=amount;$('resultStats').textContent=`${progress.completed} Aufträge erledigt · ${progress.credits} CR`;$('resultNext').textContent=button;$('resultNext').onclick=()=>{summary.classList.remove('show');callback()};summary.classList.add('show')}
function resetPart(){if(!selected)return;selected.userData.target.copy(selected.userData.home);selected=null}function returnToGarage(){resetPart();phase='inspect';speed=0;distance=0;steering=0;car.position.set(0,0,0);car.rotation.y=0;workshop.visible=true;track.visible=false;orbit.enabled=true;camera.position.set(6,4.5,8);orbit.target.set(0,1,0);orbit.update();dash.classList.remove('on');$('action').disabled=true;$('action').textContent='Teil wählen';hud();message(`Auftrag ${progress.completed+1}: ${job().issue} – ${job().name}. Prüfen: Teil anklicken → demontieren → prüfen.`)}
renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!started||phase!=='inspect'||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)return;const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(pickables,false)[0];if(!hit)return;selected=hit.object.userData.part;phase='selected';$('action').textContent='Teil demontieren';$('action').disabled=false;const names={vr:'Rad vorne rechts',vl:'Rad vorne links',hr:'Rad hinten rechts',hl:'Rad hinten links',lightL:'Scheinwerfer vorne links',lightR:'Scheinwerfer vorne rechts',battery:'Batterie im Motorraum'};message(`${names[selected.userData.id]} gewählt. Erst demontieren, dann prüfen.`)});
$('action').onclick=()=>{if(phase==='selected'){const h=selected.userData.home;selected.userData.target.set(h.x+(h.x>=0?1.15:-1.15),h.y+.45,h.z+.2);phase='removed';$('action').textContent='Ausgebautes Teil prüfen';message('Teil ist ausgebaut. Prüfe jetzt den Zustand.')}else if(phase==='removed'){if(selected.userData.id===job().part){phase='fault';$('action').textContent='Ersatzteil montieren';message(`Fehler bestätigt: ${job().issue}. Ersatzteil einbauen.`)}else{phase='good';$('action').textContent='Teil wieder montieren';message('Teil in Ordnung. Baue es wieder ein und prüfe weiter.')}}else if(phase==='good'){resetPart();phase='inspect';$('action').disabled=true;$('action').textContent='Teil wählen';message('Teil wieder montiert. Suche das defekte Bauteil.')}else if(phase==='fault'){selected.userData.target.copy(selected.userData.home);selected=null;phase='ready';$('action').disabled=true;result('REPARATUR ABGESCHLOSSEN','Ersatzteil montiert',`${job().name} wurde geprüft, ersetzt und wieder eingebaut. Jetzt folgt die Probefahrt.`,'✓','PROBEFAHRT STARTEN',beginDrive)}};
function beginDrive(){phase='drive';workshop.visible=false;track.visible=true;car.position.set(0,0,6);orbit.enabled=false;dash.classList.add('on');message('Probefahrt: 300 Meter fahren. Tacho rechts unten beobachten.')}function finish(){phase='done';speed=0;dash.classList.remove('on');const reward=job().reward;progress.completed++;progress.credits+=reward;try{localStorage.setItem('garage-drive-progress-v1',JSON.stringify(progress))}catch{}result('QUALITÄTSPRÜFUNG BESTANDEN','Auftrag abgeschlossen',`Probefahrt bestanden. Nächster Auftrag: ${job().name}.`,`+${reward} CR`,'NÄCHSTEN AUFTRAG ANNEHMEN',returnToGarage)}
$('reset').onclick=()=>{summary.classList.remove('show');returnToGarage()};$('camera').onclick=()=>cameraMode=(cameraMode+1)%3;window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='enter'&&!started&&!$('enter').disabled){start();return}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)&&phase==='drive'){keys.add(k);e.preventDefault()}if(k==='c'&&started)cameraMode=(cameraMode+1)%3});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{if(phase!=='drive')return;e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(k)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(k))});
function resize(){const w=view.clientWidth,h=view.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}new ResizeObserver(resize).observe(view);function start(){if(started)return;started=true;$('intro').classList.add('off');returnToGarage();resize();renderer.setAnimationLoop(loop)}$('enter').onclick=start;
function loop(t){const dt=Math.min((t-(last||t))/1000,.05);last=t;for(const g of parts.values())g.position.lerp(g.userData.target,Math.min(1,dt*8));if(phase==='drive'){const gas=keys.has('w')||keys.has('arrowup'),brake=keys.has('s')||keys.has('arrowdown');speed=T.MathUtils.clamp(speed+(gas?12:brake?-25:-5)*dt,0,32);for(const l of stops)l.intensity=brake?16:2;const steer=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));steering=T.MathUtils.clamp(steering+steer*dt*.5,-.45,.45);car.position.x=T.MathUtils.clamp(car.position.x+Math.sin(steering)*speed*dt,-7,7);car.position.z-=Math.cos(steering)*speed*dt;distance+=speed*dt;track.position.z=car.position.z+36;car.rotation.y=-steering;const offset=cameraMode===0?new T.Vector3(0,3.8,7):cameraMode===1?new T.Vector3(0,2.6,4):new T.Vector3(0,1.65,.7);camera.position.copy(car.position).add(offset);camera.lookAt(car.position.x,1,car.position.z-8);const kmh=Math.round(speed*3.6);$('kmh').textContent=kmh;$('needle').style.transform=`translateX(-50%) rotate(${-120+Math.min(kmh,120)*2}deg)`;$('speed').textContent=`${kmh} km/h · ${Math.min(300,Math.floor(distance))}/300 m`;if(distance>=300)finish()}else orbit.update();renderer.render(scene,camera)}
resize();setTimeout(()=>{$('loading').textContent='FAHRZEUG BEREIT · WERKSTATT ÖFFNEN';$('enter').disabled=false},2400);