// 2026-10-01 11:49 CEST: Karosserie, Felgen, Licht und Antenne überarbeitet; Auftragsfolge, Ergebnisfenster und lokaler Fortschritt ergänzt.
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
const $=id=>document.getElementById(id),host=$('view'),keys=new Set(),ray=new T.Raycaster(),pointer=new T.Vector2();
const jobs=[{title:'Bremsanlage vorne rechts',fault:'Bremsbelag vorne rechts verschlissen',part:'Bremsbelag vorne rechts',wheel:'vr',reward:180},{title:'Hinterrad links',fault:'Reifen hinten links beschädigt',part:'Reifen hinten links',wheel:'hl',reward:230},{title:'Bremsanlage vorne links',fault:'Bremsbelag vorne links verschlissen',part:'Bremsbelag vorne links',wheel:'vl',reward:260}];
const saveKey='garage-drive-progress-v1';let progress={completed:0,credits:0};try{const stored=JSON.parse(localStorage.getItem(saveKey)||'null');if(stored&&Number.isSafeInteger(stored.completed)&&stored.completed>=0&&Number.isSafeInteger(stored.credits)&&stored.credits>=0)progress=stored}catch{};
let phase='inspect',chosen=null,speed=0,travel=0,heading=0,cameraMode=0,last=0,started=false,down=null;const wheels=[],rims=[];
const scene=new T.Scene();scene.background=new T.Color('#192c40');scene.fog=new T.Fog('#192c40',28,100);const cam=new T.PerspectiveCamera(58,1,.1,180);cam.position.set(6,4.5,8);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;host.append(renderer.domElement);
const orbit=new OrbitControls(cam,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;orbit.minDistance=3.4;orbit.maxDistance=15;orbit.maxPolarAngle=1.45;
const mat=(c,m=0,r=.55)=>new T.MeshStandardMaterial({color:c,metalness:m,roughness:r}),paint=mat('#a82235',.58,.25),trim=mat('#101b25',.35,.42),chrome=mat('#bdcbd4',.82,.22),windowMat=mat('#274a60',.32,.19),rubber=mat('#11161b',0,.96),rimMat=mat('#aab9c2',.9,.26),road=mat('#34414d'),mint=mat('#55dfc6',.3,.3),lamp=new T.MeshStandardMaterial({color:'#effaff',emissive:'#d4f3ff',emissiveIntensity:3}),rearLamp=new T.MeshStandardMaterial({color:'#ff323b',emissive:'#ff2428',emissiveIntensity:1.8});
function mesh(parent,geo,m,x=0,y=0,z=0){const a=new T.Mesh(geo,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}function box(parent,w,h,d,x,y,z,m){return mesh(parent,new T.BoxGeometry(w,h,d),m,x,y,z)}function rounded(parent,w,h,d,x,y,z,m,r=.15){return mesh(parent,new RoundedBoxGeometry(w,h,d,4,r),m,x,y,z)}
scene.add(new T.HemisphereLight('#cbe9ff','#25343f',2));const sun=new T.DirectionalLight('#fff0de',3.2);sun.position.set(-5,10,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-20;sun.shadow.camera.right=20;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;scene.add(sun);
const ground=box(scene,120,.15,120,0,-.14,0,mat('#304d44'));ground.castShadow=false;const garage=new T.Group();scene.add(garage);box(garage,17,.14,18,0,-.01,0,mat('#435160'));box(garage,17,7,.3,0,3.4,-9,mat('#263a4d'));for(const x of [-8.4,8.4])box(garage,.3,7,18,x,3.4,0,mat('#263a4d'));for(const x of [-5,5]){rounded(garage,3,.11,.55,x,6.6,-3,new T.MeshStandardMaterial({color:'#dffff4',emissive:'#52dfc6',emissiveIntensity:2}));const fill=new T.PointLight('#83ffe4',24,9);fill.position.set(x,5,-3);garage.add(fill)}for(const x of [-2.1,2.1])box(garage,.08,.01,14,x,.07,0,mint);
const track=new T.Group();track.visible=false;scene.add(track);box(track,18,.04,110,0,.01,-36,road);for(let z=-85;z<20;z+=8)box(track,.12,.045,3,0,.06,z,mat('#f5e6ac'));for(const x of [-8.7,8.7])box(track,.17,.05,110,x,.06,-36,mat('#fff4dc'));
const car=new T.Group();scene.add(car);rounded(car,2.14,.54,4.42,0,.86,0,paint,.21);rounded(car,2.07,.19,1.33,0,1.10,-1.55,paint,.13);rounded(car,2.07,.22,1.04,0,1.06,1.66,paint,.12);rounded(car,1.75,.62,2.12,0,1.40,-.19,paint,.24);rounded(car,1.61,.31,.92,0,1.58,-1.01,windowMat,.06);rounded(car,1.61,.29,.65,0,1.55,.65,windowMat,.06);for(const x of [-.91,.91]){rounded(car,.05,.32,1.15,x,1.51,-.19,windowMat,.02);rounded(car,.22,.12,.30,x*1.11,1.37,-.95,paint,.05)}rounded(car,2.03,.24,.16,0,.69,-2.2,trim,.06);rounded(car,2.03,.24,.16,0,.69,2.2,trim,.06);rounded(car,1.02,.27,.05,0,.76,-2.29,trim,.03);for(const x of [-.34,-.17,0,.17,.34])box(car,.035,.22,.02,x,.75,-2.33,chrome);for(const z of [-1.48,1.48])for(const x of [-.97,.97])rounded(car,.14,.2,.55,x,1.01,z,paint,.06);
const headLights=[],brakeLights=[];for(const x of [-.79,.79]){rounded(car,.42,.12,.055,x,1.03,-2.22,lamp,.035);const beam=new T.SpotLight('#c8efff',65,18,Math.PI/7,.55,2);beam.position.set(x,1.05,-2.25);beam.target.position.set(x,.2,-10);car.add(beam,beam.target);headLights.push(beam);rounded(car,.40,.14,.05,x,1.02,2.23,rearLamp,.025);const stop=new T.PointLight('#ff3138',0,5);stop.position.set(x,1,2.25);car.add(stop);brakeLights.push(stop)}
const antenna=mesh(car,new T.CylinderGeometry(.012,.022,.72,8),trim,.64,2.06,.59);antenna.rotation.z=.18;mesh(car,new T.SphereGeometry(.04,8,8),chrome,.51,2.4,.59);
for(const [id,x,z] of [['vl',-1.17,-1.45],['vr',1.17,-1.45],['hl',-1.17,1.45],['hr',1.17,1.45]]){const tire=mesh(car,new T.CylinderGeometry(.39,.39,.26,32),rubber,x,.4,z);tire.rotation.z=Math.PI/2;tire.userData.id=id;wheels.push(tire);const rim=mesh(car,new T.CylinderGeometry(.245,.245,.278,32),rimMat,x,.4,z);rim.rotation.z=Math.PI/2;rim.userData.tire=tire;car.add(rim);wheels.push(rim);const ring=mesh(car,new T.TorusGeometry(.21,.024,8,32),chrome,x+(x>0?.15:-.15),.4,z);ring.rotation.y=Math.PI/2;rim.userData.ring=ring;rims.push(ring);for(let s=0;s<6;s++){const spoke=box(car,.02,.048,.38,x+(x>0?.158:-.158),.4,z,rimMat);spoke.rotation.x=s*Math.PI/6;rims.push(spoke)}}
const style=document.createElement('style');style.textContent='header,.hud,.controls{background:linear-gradient(115deg,#132b3a,#0c1728)!important;border-bottom:1px solid #4de0c437;box-shadow:0 8px 20px #0005}#view{background:radial-gradient(circle,#35566b,#0c1828)}.hud{gap:18px!important}.hud p{color:#e3f3f4}.hud button,.controls button{box-shadow:0 3px 0 #207267,0 0 15px #43dab421}#summary{position:fixed;inset:0;z-index:8;background:#050a16c9;display:none;place-items:center;padding:18px;backdrop-filter:blur(10px)}#summary.show{display:grid}.result{width:min(500px,92vw);padding:32px;border:1px solid #5ce6cb88;border-radius:24px;background:linear-gradient(145deg,#203c4c,#0b1526 75%);box-shadow:0 0 80px #50e9d22b;text-align:center}.result h2{font-size:clamp(1.8rem,6vw,3rem);margin:.2em 0;color:#fff}.result .tag{color:#67e9cf;letter-spacing:.18em;font-weight:800}.result p{color:#bfd2db;line-height:1.6}.result button{background:#68e7ce;padding:15px 23px;border:0;border-radius:12px;font-weight:900;cursor:pointer}.result .amount{font-size:2rem;color:#ffd484;font-weight:900}';document.head.append(style);
const overlay=document.createElement('section');overlay.id='summary';overlay.innerHTML='<div class="result"><div class="tag" id="resultTag"></div><h2 id="resultTitle"></h2><p id="resultText"></p><div class="amount" id="resultAmount"></div><p id="resultStats"></p><button id="resultNext"></button></div>';document.body.append(overlay);
function job(){return jobs[progress.completed%jobs.length]}function message(s){$('message').textContent=s}function updateHud(){document.querySelector('header span').textContent=`AUFTRAG ${String(progress.completed+1).padStart(3,'0')} · ${job().title.toUpperCase()}`;$('speed').textContent=`${progress.credits} CR · WERKSTATT`}
function showResult(tag,title,text,amount,button,onClick){$('resultTag').textContent=tag;$('resultTitle').textContent=title;$('resultText').textContent=text;$('resultAmount').textContent=amount;$('resultStats').textContent=`${progress.completed} Aufträge abgeschlossen · ${progress.credits} CR Guthaben`;$('resultNext').textContent=button;$('resultNext').onclick=()=>{overlay.classList.remove('show');onClick()};overlay.classList.add('show')}
function save(){try{localStorage.setItem(saveKey,JSON.stringify(progress))}catch{}}function startJob(){phase='inspect';chosen=null;speed=0;travel=0;heading=0;car.position.set(0,0,0);car.rotation.y=0;garage.visible=true;track.visible=false;orbit.enabled=true;cam.position.set(6,4.5,8);orbit.target.set(0,1,0);orbit.update();for(const wheel of wheels.filter(w=>w.userData.id))wheel.material=rubber;for(const l of headLights)l.intensity=65;for(const l of brakeLights)l.intensity=0;$('action').disabled=true;$('action').textContent='Diagnose';updateHud();message(`Auftrag ${progress.completed+1}: ${job().fault}. Prüfe die Räder am Fahrzeug.`)}
renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!started||phase!=='inspect'||overlay.classList.contains('show')||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)return;const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,cam);const hit=ray.intersectObjects(wheels,false)[0];if(!hit)return;const wheel=hit.object.userData.tire||hit.object;if(chosen)chosen.material=rubber;chosen=wheel;wheel.material=mint;$('action').disabled=false;$('action').textContent='Befund bestätigen';message(wheel.userData.id===job().wheel?`Fehler gefunden: ${job().fault}.`:'Dieses Rad ist in Ordnung. Suche weiter.')});
$('action').onclick=()=>{if(phase==='inspect'){if(chosen?.userData.id!==job().wheel){message('Das ist nicht das defekte Rad. Prüfe die anderen Räder.');return}phase='repair';$('action').textContent='Teil ersetzen';message(`Reparaturschritt: ${job().part} ersetzen.`)}else if(phase==='repair'){phase='ready';chosen.material=rubber;$('action').disabled=true;showResult('REPARATUR ABGESCHLOSSEN','Fahrzeug bereit',`${job().part} ersetzt. Die Reparatur ist erledigt – jetzt bestätigt eine 300-m-Probefahrt das Ergebnis.`,'✓','PROBEFAHRT STARTEN',beginDrive)}};
function beginDrive(){phase='drive';garage.visible=false;track.visible=true;car.position.set(0,0,6);orbit.enabled=false;message('Probefahrt läuft: 300 Meter fahren und die Bremsen testen.')}function complete(){phase='done';speed=0;const earned=job().reward;progress.completed++;progress.credits+=earned;save();for(const l of brakeLights)l.intensity=8;showResult('QUALITÄTSPRÜFUNG BESTANDEN','Auftrag abgeschlossen',`Die Probefahrt ist geschafft. Als Nächstes wartet: ${job().title}.`,`+${earned} CR`,'NÄCHSTEN AUFTRAG ANNEHMEN',startJob)}
$('reset').onclick=()=>{overlay.classList.remove('show');startJob()};$('camera').onclick=()=>cameraMode=(cameraMode+1)%3;
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='enter'&&!started&&!$('enter').disabled){start();return}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)&&phase==='drive'){keys.add(k);e.preventDefault()}if(k==='c'&&started)cameraMode=(cameraMode+1)%3});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{if(phase!=='drive')return;e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(k)});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>keys.delete(k))});
function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;cam.aspect=w/h;cam.updateProjectionMatrix();renderer.setSize(w,h)}new ResizeObserver(resize).observe(host);function start(){if(started)return;started=true;$('intro').classList.add('off');startJob();resize();renderer.setAnimationLoop(loop)}$('enter').onclick=start;
function loop(t){const dt=Math.min((t-(last||t))/1000,.05);last=t;if(phase==='drive'){const gas=keys.has('w')||keys.has('arrowup'),brake=keys.has('s')||keys.has('arrowdown');speed=T.MathUtils.clamp(speed+(gas?12:brake?-25:-5)*dt,0,32);for(const l of brakeLights)l.intensity=brake?16:2;const steer=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));heading=T.MathUtils.clamp(heading+steer*dt*.5,-.45,.45);car.position.x=T.MathUtils.clamp(car.position.x+Math.sin(heading)*speed*dt,-7,7);car.position.z-=Math.cos(heading)*speed*dt;travel+=speed*dt;track.position.z=car.position.z+36;car.rotation.y=-heading;const offset=cameraMode===0?new T.Vector3(0,3.8,7):cameraMode===1?new T.Vector3(0,2.6,4):new T.Vector3(0,1.65,.7);cam.position.copy(car.position).add(offset);cam.lookAt(car.position.x,1,car.position.z-8);$('speed').textContent=`${Math.round(speed*3.6)} km/h · ${Math.min(300,Math.floor(travel))}/300 m`;if(travel>=300)complete()}else orbit.update();renderer.render(scene,cam)}
resize();setTimeout(()=>{$('loading').textContent='FAHRZEUG BEREIT · WERKSTATT ÖFFNEN';$('enter').disabled=false},2400);