// 2026-10-01 11:45 CEST: Raycast-Radklick repariert; 3D-Werkstatt und Probefahrt mit einmaligem Enter-Start am Index eingebunden.
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),host=$('view'),keys=new Set(),ray=new T.Raycaster(),pointer=new T.Vector2(),wheels=[];
let phase='inspect',chosen=null,speed=0,travel=0,heading=0,cameraMode=0,last=0,started=false;
const scene=new T.Scene();scene.background=new T.Color('#20334a');scene.fog=new T.Fog('#20334a',30,95);const cam=new T.PerspectiveCamera(60,1,.1,180);cam.position.set(6,5,8);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;host.append(renderer.domElement);
const orbit=new OrbitControls(cam,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;orbit.minDistance=3;orbit.maxDistance=14;orbit.maxPolarAngle=1.48;
const mat=(c,m=0,r=.55)=>new T.MeshStandardMaterial({color:c,metalness:m,roughness:r}),red=mat('#c84949',.55,.27),dark=mat('#111820'),steel=mat('#98abb9',.7,.3),glass=mat('#46708a',.25,.2),road=mat('#333c48'),mint=mat('#55dfc6',.3,.3);
function cube(parent,w,h,d,x,y,z,m){const a=new T.Mesh(new T.BoxGeometry(w,h,d),m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
scene.add(new T.HemisphereLight('#cce7ff','#283342',2));const sun=new T.DirectionalLight('#fff0d8',3);sun.position.set(-5,12,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;scene.add(sun);
const ground=cube(scene,100,.15,100,0,-.12,0,mat('#385341'));ground.castShadow=false;const garage=new T.Group();scene.add(garage);cube(garage,16,.15,16,0,-.01,0,mat('#4a5663'));cube(garage,16,6,.25,0,2.9,-8,mat('#293c51'));cube(garage,.25,6,16,-8,2.9,0,mat('#293c51'));cube(garage,.25,6,16,8,2.9,0,mat('#293c51'));for(const x of [-5,5])cube(garage,3,.14,.5,x,5.8,-4,mint);
const track=new T.Group();track.visible=false;scene.add(track);cube(track,18,.03,100,0,.01,-34,road);for(let z=-78;z<15;z+=8)cube(track,.12,.04,3,0,.05,z,mat('#f7e8bb'));for(const x of [-8.8,8.8])cube(track,.2,.04,100,x,.05,-34,mat('#f5e3bc'));
const car=new T.Group();scene.add(car);cube(car,2.2,.58,4.3,0,.85,0,red);cube(car,1.85,.57,2,0,1.39,-.25,red);cube(car,1.7,.04,1,0,1.71,-.25,glass);cube(car,1.75,.23,.55,0,1.45,1,glass);cube(car,1.75,.23,.55,0,1.45,-1.18,glass);
for(const x of [-1.16,1.16])for(const z of [-1.4,1.4]){const wheel=new T.Mesh(new T.CylinderGeometry(.4,.4,.29,24),dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.4,z);wheel.castShadow=true;wheel.userData.bad=x>0&&z>0;car.add(wheel);wheels.push(wheel);const rim=new T.Mesh(new T.CylinderGeometry(.24,.24,.3,24),steel);rim.rotation.z=Math.PI/2;rim.position.copy(wheel.position);rim.userData.wheel=wheel;car.add(rim);wheels.push(rim)}
for(const x of [-.78,.78]){cube(car,.34,.14,.04,x,.95,2.16,mat('#fff3c2'));cube(car,.34,.14,.04,x,.95,-2.16,mat('#e92930'))}
function msg(s){$('message').textContent=s}function select(w){if(chosen)chosen.material=dark;chosen=w;w.material=mint;$('action').disabled=false;msg(w.userData.bad?'Befund: Bremse vorne rechts verschlissen. Diagnose bestätigen.':'Dieses Rad ist in Ordnung. Weitere Räder prüfen.');$('action').textContent='Diagnose bestätigen'}
renderer.domElement.addEventListener('click',e=>{if(phase!=='inspect'||!started)return;const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,cam);const hit=ray.intersectObjects(wheels,false)[0];if(hit){const wheel=hit.object.userData.wheel||hit.object;select(wheel)}});
$('action').onclick=()=>{if(phase==='inspect'){if(!chosen?.userData.bad){msg('Fehler noch nicht gefunden: Prüfe das vordere rechte Rad.');return}phase='repair';$('action').textContent='Bremsbelag ersetzen';msg('Diagnose bestätigt. Ersetze jetzt den Bremsbelag vorne rechts.')}else if(phase==='repair'){phase='ready';chosen.material=dark;$('action').textContent='Probefahrt starten';msg('Belag ersetzt. Starte die Probefahrt über 300 Meter.')}else if(phase==='ready'){phase='drive';chosen=null;garage.visible=false;track.visible=true;car.position.set(0,0,6);orbit.enabled=false;$('action').disabled=true;msg('Probefahrt: Gas geben und 300 Meter zurücklegen.')}};
$('reset').onclick=()=>location.reload();$('camera').onclick=()=>cameraMode=(cameraMode+1)%3;
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='enter'&&!started&&!$('enter').disabled){start();return}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){if(phase==='drive'){keys.add(k);e.preventDefault()}}if(k==='c'&&started)cameraMode=(cameraMode+1)%3});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{if(phase!=='drive')return;e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(k)});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>keys.delete(k))});
function start(){if(started)return;started=true;$('intro').classList.add('off');renderer.setAnimationLoop(loop);resize()}$('enter').onclick=start;
function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;cam.aspect=w/h;cam.updateProjectionMatrix();renderer.setSize(w,h)}new ResizeObserver(resize).observe(host);resize();
function loop(t){const dt=Math.min((t-(last||t))/1000,.05);last=t;if(phase==='drive'){const gas=keys.has('w')||keys.has('arrowup'),brake=keys.has('s')||keys.has('arrowdown');speed=T.MathUtils.clamp(speed+(gas?13:brake?-25:-5)*dt,0,32);const steer=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));heading=T.MathUtils.clamp(heading+steer*dt*.55,-.5,.5);car.position.x=T.MathUtils.clamp(car.position.x+Math.sin(heading)*speed*dt,-7,7);car.position.z-=Math.cos(heading)*speed*dt;travel+=speed*dt;track.position.z=car.position.z+34;car.rotation.y=-heading;const offset=cameraMode===0?new T.Vector3(0,4,8):cameraMode===1?new T.Vector3(0,2.6,4):new T.Vector3(0,1.65,.65);cam.position.copy(car.position).add(offset);cam.lookAt(car.position.x,1,car.position.z-8);$('speed').textContent=`${Math.round(speed*3.6)} km/h · ${Math.min(300,Math.floor(travel))}/300 m`;if(travel>=300){phase='done';speed=0;msg('Auftrag abgeschlossen: Reparatur und Probefahrt bestanden!')}}else orbit.update();renderer.render(scene,cam)}
setTimeout(()=>{$('loading').textContent='FAHRZEUG BEREIT · WERKSTATT ÖFFNEN';$('enter').disabled=false},2400);